# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created: Wed Dec 10 16:52:30 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_demo_qt(object):
    def setupUi(self, demo_qt):
        demo_qt.setObjectName(_fromUtf8("demo_qt"))
        demo_qt.resize(1062, 680)
        self.centralWidget = QtGui.QWidget(demo_qt)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.AOMode = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.AOMode.setFont(font)
        self.AOMode.setObjectName(_fromUtf8("AOMode"))
        self.gridLayout_2.addWidget(self.AOMode, 0, 1, 1, 2)
        self.loadfitsButton = QtGui.QToolButton(self.centralWidget)
        self.loadfitsButton.setObjectName(_fromUtf8("loadfitsButton"))
        self.gridLayout_2.addWidget(self.loadfitsButton, 1, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_2.addWidget(self.textEdit, 1, 1, 1, 1)
        self.okButton = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.gridLayout_2.addWidget(self.okButton, 1, 2, 1, 1)
        self.ComboBox = QtGui.QComboBox(self.centralWidget)
        self.ComboBox.setObjectName(_fromUtf8("ComboBox"))
        self.gridLayout_2.addWidget(self.ComboBox, 1, 3, 1, 1)
        self.resetCombobox = QtGui.QPushButton(self.centralWidget)
        self.resetCombobox.setObjectName(_fromUtf8("resetCombobox"))
        self.gridLayout_2.addWidget(self.resetCombobox, 2, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(309, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton = QtGui.QPushButton(self.centralWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.twoStateButton = QtGui.QPushButton(self.centralWidget)
        self.twoStateButton.setCheckable(False)
        self.twoStateButton.setObjectName(_fromUtf8("twoStateButton"))
        self.gridLayout_3.addWidget(self.twoStateButton, 1, 0, 1, 1)
        self.winNumber = QtGui.QSpinBox(self.centralWidget)
        self.winNumber.setMinimum(1)
        self.winNumber.setMaximum(2)
        self.winNumber.setProperty("value", 1)
        self.winNumber.setObjectName(_fromUtf8("winNumber"))
        self.gridLayout_3.addWidget(self.winNumber, 2, 1, 1, 1)
        self.plotRandom = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotRandom.sizePolicy().hasHeightForWidth())
        self.plotRandom.setSizePolicy(sizePolicy)
        self.plotRandom.setObjectName(_fromUtf8("plotRandom"))
        self.gridLayout_3.addWidget(self.plotRandom, 2, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.AOMode_2 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.AOMode_2.setFont(font)
        self.AOMode_2.setObjectName(_fromUtf8("AOMode_2"))
        self.verticalLayout_2.addWidget(self.AOMode_2)
        self.radioButton_1 = QtGui.QRadioButton(self.centralWidget)
        self.radioButton_1.setObjectName(_fromUtf8("radioButton_1"))
        self.verticalLayout_2.addWidget(self.radioButton_1)
        self.radioButton_2 = QtGui.QRadioButton(self.centralWidget)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.centralWidget)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.centralWidget)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.window2 = MatplotlibWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window2.sizePolicy().hasHeightForWidth())
        self.window2.setSizePolicy(sizePolicy)
        self.window2.setMinimumSize(QtCore.QSize(200, 200))
        self.window2.setObjectName(_fromUtf8("window2"))
        self.WFSUsed_2 = QtGui.QLabel(self.window2)
        self.WFSUsed_2.setGeometry(QtCore.QRect(0, 0, 99, 26))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WFSUsed_2.setFont(font)
        self.WFSUsed_2.setObjectName(_fromUtf8("WFSUsed_2"))
        self.gridLayout.addWidget(self.window2, 0, 1, 1, 1)
        self.window1 = MatplotlibWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window1.sizePolicy().hasHeightForWidth())
        self.window1.setSizePolicy(sizePolicy)
        self.window1.setMinimumSize(QtCore.QSize(200, 200))
        self.window1.setObjectName(_fromUtf8("window1"))
        self.WFSUsed = QtGui.QLabel(self.window1)
        self.WFSUsed.setGeometry(QtCore.QRect(0, 0, 99, 26))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WFSUsed.setFont(font)
        self.WFSUsed.setObjectName(_fromUtf8("WFSUsed"))
        self.gridLayout.addWidget(self.window1, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.dialogBox = QtGui.QTextEdit(self.centralWidget)
        self.dialogBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.dialogBox.setFrameShape(QtGui.QFrame.StyledPanel)
        self.dialogBox.setObjectName(_fromUtf8("dialogBox"))
        self.verticalLayout.addWidget(self.dialogBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        demo_qt.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(demo_qt)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        demo_qt.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(demo_qt)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1062, 34))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuShow_hide_Dialog_Box = QtGui.QMenu(self.menuBar)
        self.menuShow_hide_Dialog_Box.setObjectName(_fromUtf8("menuShow_hide_Dialog_Box"))
        demo_qt.setMenuBar(self.menuBar)
        self.open_file = QtGui.QAction(demo_qt)
        self.open_file.setCheckable(True)
        self.open_file.setObjectName(_fromUtf8("open_file"))
        self.start_zSim = QtGui.QAction(demo_qt)
        self.start_zSim.setCheckable(True)
        self.start_zSim.setChecked(True)
        self.start_zSim.setText(_fromUtf8("system ./zSim_bin"))
        self.start_zSim.setObjectName(_fromUtf8("start_zSim"))
        self.actionShow_DialogBox = QtGui.QAction(demo_qt)
        self.actionShow_DialogBox.setObjectName(_fromUtf8("actionShow_DialogBox"))
        self.actionHide_DialogBox = QtGui.QAction(demo_qt)
        self.actionHide_DialogBox.setObjectName(_fromUtf8("actionHide_DialogBox"))
        self.menuShow_hide_Dialog_Box.addSeparator()
        self.menuShow_hide_Dialog_Box.addSeparator()
        self.menuShow_hide_Dialog_Box.addAction(self.actionShow_DialogBox)
        self.menuShow_hide_Dialog_Box.addAction(self.actionHide_DialogBox)
        self.menuBar.addAction(self.menuShow_hide_Dialog_Box.menuAction())

        self.retranslateUi(demo_qt)
        QtCore.QObject.connect(self.actionHide_DialogBox, QtCore.SIGNAL(_fromUtf8("activated()")), self.dialogBox.hide)
        QtCore.QObject.connect(self.actionShow_DialogBox, QtCore.SIGNAL(_fromUtf8("activated()")), self.dialogBox.show)
        QtCore.QMetaObject.connectSlotsByName(demo_qt)

    def retranslateUi(self, demo_qt):
        demo_qt.setWindowTitle(_translate("demo_qt", "demo", None))
        self.AOMode.setText(_translate("demo_qt", "Add this text in combobox:", None))
        self.loadfitsButton.setText(_translate("demo_qt", "Load fits file", None))
        self.loadfitsButton.setShortcut(_translate("demo_qt", "Ctrl+S", None))
        self.okButton.setText(_translate("demo_qt", "ok", None))
        self.resetCombobox.setText(_translate("demo_qt", "resetComboBox", None))
        self.pushButton.setText(_translate("demo_qt", "Push button", None))
        self.twoStateButton.setText(_translate("demo_qt", "2 state Button", None))
        self.plotRandom.setText(_translate("demo_qt", "Plot random image in window #", None))
        self.AOMode_2.setText(_translate("demo_qt", "Who is the best?", None))
        self.radioButton_1.setText(_translate("demo_qt", "Eric Gendron?", None))
        self.radioButton_2.setText(_translate("demo_qt", "Obiwan kenobi?", None))
        self.radioButton_3.setText(_translate("demo_qt", "Fabrice Vidal?", None))
        self.radioButton_4.setText(_translate("demo_qt", "Zoltan hubert?", None))
        self.WFSUsed_2.setText(_translate("demo_qt", "window 2", None))
        self.WFSUsed.setText(_translate("demo_qt", "window 1", None))
        self.label_2.setText(_translate("demo_qt", "Dialog box:", None))
        self.menuShow_hide_Dialog_Box.setTitle(_translate("demo_qt", "Show/hide Dialog Box", None))
        self.open_file.setText(_translate("demo_qt", "QString s = QFileDialog::getOpenFileName(\"./\", \"All Files (*.*)\", this, \"open file dialog\", \"Choose a file...\" );\n"
"    inputEdit->setText(s);\n"
"", None))
        self.start_zSim.setToolTip(_translate("demo_qt", "start zSim", None))
        self.actionShow_DialogBox.setText(_translate("demo_qt", "Show DialogBox", None))
        self.actionHide_DialogBox.setText(_translate("demo_qt", "Hide DialogBox", None))

from matplotlibwidget import MatplotlibWidget
